export {}
// generated by typed-config.js
declare module "atom" {
  interface ConfigValues {
    "atom-typescript.unusedAsInfo": boolean
    "atom-typescript.autocompletionSuggestionPriority": number
    "atom-typescript.locale": string
    "atom-typescript.buildStatusTimeout": number
    "atom-typescript.showSemanticView": boolean
    "atom-typescript": {
      unusedAsInfo: boolean
      autocompletionSuggestionPriority: number
      locale: string
      buildStatusTimeout: number
      showSemanticView: boolean
    }
  }
}
