export {}
// generated by typed-config.js
declare module "atom" {
  interface ConfigValues {
    "atom-typescript.unusedAsInfo": boolean
    "atom-typescript.autocompletionSuggestionPriority": number
    "atom-typescript.locale": string
    "atom-typescript.preferBuiltinTooltips": boolean
    "atom-typescript.preferBuiltinSigHelp": boolean
    "atom-typescript.buildStatusTimeout": number
    "atom-typescript.showSemanticView": boolean
    "atom-typescript.tooltipDelay": number
    "atom-typescript.ignoredDiagnosticCodes": string[]
    "atom-typescript.ignoreUnusedSuggestionDiagnostics": boolean
    "atom-typescript.suppressAllDiagnostics": boolean
    "atom-typescript": {
      unusedAsInfo: boolean
      autocompletionSuggestionPriority: number
      locale: string
      preferBuiltinTooltips: boolean
      preferBuiltinSigHelp: boolean
      buildStatusTimeout: number
      showSemanticView: boolean
      tooltipDelay: number
      ignoredDiagnosticCodes: string[]
      ignoreUnusedSuggestionDiagnostics: boolean
      suppressAllDiagnostics: boolean
    }
  }
}
